name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: cathand/woori-forei-be
          stage: main
          yaml: >
            name: woori-forei-be

            app: java@17

            options:
              ports: 8080
              env:
                - name: PROD_DB_PASSWORD
                  value: ${{ secrets.PROD_DB_PASSWORD }}
                - name: PROD_DB_URL
                  value: ${{ secrets.PROD_DB_URL }}
                - name: PROD_DB_USER
                  value: ${{ secrets.PROD_DB_USER }}
                - name: ADMIN_SECRET_CODE
                  value: ${{ secrets.ADMIN_SECRET_CODE }}
                - name: AUTH_KEY
                  value: ${{ secrets.AUTH_KEY }}
                - name: GMAIL_PASSWORD
                  value: ${{ secrets.GMAIL_PASSWORD }}
                - name: GMAIL_USERNAME
                  value: ${{ secrets.GMAIL_USERNAME }}
                - name: JWT_SECRET_KEY
                  value: ${{ secrets.JWT_SECRET_KEY }}
                - name: GOOGLE_CLIENT_ID
                  value: ${{ secrets.GOOGLE_CLIENT_ID }}
                - name: GOOGLE_CLIENT_SECRET
                  value: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                - name: S3_ACCESS_KEY
                  value: ${{ secrets.S3_ACCESS_KEY }}
                - name: S3_NAME
                  value: ${{ secrets.S3_NAME }}
                - name: S3_REGION
                  value: ${{ secrets.S3_REGION }}
                - name: SECRET_ACCESS_KEY
                  value: ${{ secrets.SECRET_ACCESS_KEY }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
